/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SequencesIndexRouteImport } from './routes/sequences.index'
import { Route as SegmentsIndexRouteImport } from './routes/segments.index'
import { Route as SequencesSequenceIdRouteImport } from './routes/sequences.$sequenceId'
import { Route as SegmentsSegmentIdRouteImport } from './routes/segments.$segmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIndexRoute = SequencesIndexRouteImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsIndexRoute = SegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesSequenceIdRoute = SequencesSequenceIdRouteImport.update({
  id: '/sequences/$sequenceId',
  path: '/sequences/$sequenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsSegmentIdRoute = SegmentsSegmentIdRouteImport.update({
  id: '/segments/$segmentId',
  path: '/segments/$segmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/segments/': typeof SegmentsIndexRoute
  '/sequences/': typeof SequencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/segments': typeof SegmentsIndexRoute
  '/sequences': typeof SequencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/segments/': typeof SegmentsIndexRoute
  '/sequences/': typeof SequencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/segments/$segmentId'
    | '/sequences/$sequenceId'
    | '/segments/'
    | '/sequences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/segments/$segmentId'
    | '/sequences/$sequenceId'
    | '/segments'
    | '/sequences'
  id:
    | '__root__'
    | '/'
    | '/segments/$segmentId'
    | '/sequences/$sequenceId'
    | '/segments/'
    | '/sequences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SegmentsSegmentIdRoute: typeof SegmentsSegmentIdRoute
  SequencesSequenceIdRoute: typeof SequencesSequenceIdRoute
  SegmentsIndexRoute: typeof SegmentsIndexRoute
  SequencesIndexRoute: typeof SequencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/': {
      id: '/sequences/'
      path: '/sequences'
      fullPath: '/sequences/'
      preLoaderRoute: typeof SequencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/': {
      id: '/segments/'
      path: '/segments'
      fullPath: '/segments/'
      preLoaderRoute: typeof SegmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/$sequenceId': {
      id: '/sequences/$sequenceId'
      path: '/sequences/$sequenceId'
      fullPath: '/sequences/$sequenceId'
      preLoaderRoute: typeof SequencesSequenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/$segmentId': {
      id: '/segments/$segmentId'
      path: '/segments/$segmentId'
      fullPath: '/segments/$segmentId'
      preLoaderRoute: typeof SegmentsSegmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SegmentsSegmentIdRoute: SegmentsSegmentIdRoute,
  SequencesSequenceIdRoute: SequencesSequenceIdRoute,
  SegmentsIndexRoute: SegmentsIndexRoute,
  SequencesIndexRoute: SequencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
