/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SequencesIndexRouteImport } from './routes/sequences.index'
import { Route as SegmentsIndexRouteImport } from './routes/segments.index'
import { Route as CallsIndexRouteImport } from './routes/calls.index'
import { Route as SequencesSequenceIdRouteImport } from './routes/sequences.$sequenceId'
import { Route as SegmentsSegmentIdRouteImport } from './routes/segments.$segmentId'
import { Route as ReceptionSetupRouteImport } from './routes/reception.setup'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'
import { Route as CallsCallIdRouteImport } from './routes/calls.$callId'

const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIndexRoute = SequencesIndexRouteImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsIndexRoute = SegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CallsRoute,
} as any)
const SequencesSequenceIdRoute = SequencesSequenceIdRouteImport.update({
  id: '/sequences/$sequenceId',
  path: '/sequences/$sequenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsSegmentIdRoute = SegmentsSegmentIdRouteImport.update({
  id: '/segments/$segmentId',
  path: '/segments/$segmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionSetupRoute = ReceptionSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ReceptionRoute,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsCallIdRoute = CallsCallIdRouteImport.update({
  id: '/$callId',
  path: '/$callId',
  getParentRoute: () => CallsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRouteWithChildren
  '/reception': typeof ReceptionRouteWithChildren
  '/calls/$callId': typeof CallsCallIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/reception/setup': typeof ReceptionSetupRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/calls/': typeof CallsIndexRoute
  '/segments/': typeof SegmentsIndexRoute
  '/sequences/': typeof SequencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reception': typeof ReceptionRouteWithChildren
  '/calls/$callId': typeof CallsCallIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/reception/setup': typeof ReceptionSetupRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/calls': typeof CallsIndexRoute
  '/segments': typeof SegmentsIndexRoute
  '/sequences': typeof SequencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRouteWithChildren
  '/reception': typeof ReceptionRouteWithChildren
  '/calls/$callId': typeof CallsCallIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/reception/setup': typeof ReceptionSetupRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/calls/': typeof CallsIndexRoute
  '/segments/': typeof SegmentsIndexRoute
  '/sequences/': typeof SequencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calls'
    | '/reception'
    | '/calls/$callId'
    | '/contacts/$contactId'
    | '/reception/setup'
    | '/segments/$segmentId'
    | '/sequences/$sequenceId'
    | '/calls/'
    | '/segments/'
    | '/sequences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reception'
    | '/calls/$callId'
    | '/contacts/$contactId'
    | '/reception/setup'
    | '/segments/$segmentId'
    | '/sequences/$sequenceId'
    | '/calls'
    | '/segments'
    | '/sequences'
  id:
    | '__root__'
    | '/'
    | '/calls'
    | '/reception'
    | '/calls/$callId'
    | '/contacts/$contactId'
    | '/reception/setup'
    | '/segments/$segmentId'
    | '/sequences/$sequenceId'
    | '/calls/'
    | '/segments/'
    | '/sequences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRouteWithChildren
  ReceptionRoute: typeof ReceptionRouteWithChildren
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  SegmentsSegmentIdRoute: typeof SegmentsSegmentIdRoute
  SequencesSequenceIdRoute: typeof SequencesSequenceIdRoute
  SegmentsIndexRoute: typeof SegmentsIndexRoute
  SequencesIndexRoute: typeof SequencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/': {
      id: '/sequences/'
      path: '/sequences'
      fullPath: '/sequences/'
      preLoaderRoute: typeof SequencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/': {
      id: '/segments/'
      path: '/segments'
      fullPath: '/segments/'
      preLoaderRoute: typeof SegmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof CallsRoute
    }
    '/sequences/$sequenceId': {
      id: '/sequences/$sequenceId'
      path: '/sequences/$sequenceId'
      fullPath: '/sequences/$sequenceId'
      preLoaderRoute: typeof SequencesSequenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/$segmentId': {
      id: '/segments/$segmentId'
      path: '/segments/$segmentId'
      fullPath: '/segments/$segmentId'
      preLoaderRoute: typeof SegmentsSegmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/setup': {
      id: '/reception/setup'
      path: '/setup'
      fullPath: '/reception/setup'
      preLoaderRoute: typeof ReceptionSetupRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$callId': {
      id: '/calls/$callId'
      path: '/$callId'
      fullPath: '/calls/$callId'
      preLoaderRoute: typeof CallsCallIdRouteImport
      parentRoute: typeof CallsRoute
    }
  }
}

interface CallsRouteChildren {
  CallsCallIdRoute: typeof CallsCallIdRoute
  CallsIndexRoute: typeof CallsIndexRoute
}

const CallsRouteChildren: CallsRouteChildren = {
  CallsCallIdRoute: CallsCallIdRoute,
  CallsIndexRoute: CallsIndexRoute,
}

const CallsRouteWithChildren = CallsRoute._addFileChildren(CallsRouteChildren)

interface ReceptionRouteChildren {
  ReceptionSetupRoute: typeof ReceptionSetupRoute
}

const ReceptionRouteChildren: ReceptionRouteChildren = {
  ReceptionSetupRoute: ReceptionSetupRoute,
}

const ReceptionRouteWithChildren = ReceptionRoute._addFileChildren(
  ReceptionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRouteWithChildren,
  ReceptionRoute: ReceptionRouteWithChildren,
  ContactsContactIdRoute: ContactsContactIdRoute,
  SegmentsSegmentIdRoute: SegmentsSegmentIdRoute,
  SequencesSequenceIdRoute: SequencesSequenceIdRoute,
  SegmentsIndexRoute: SegmentsIndexRoute,
  SequencesIndexRoute: SequencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
